### ISSUE TITLE
undefined method `safe_load' for Psych:Module

### ISSUE THREAD

**Issue by trinistry** [DragonBox/u3d#156]
Hello,
this is what I am getting on "u3d run" on AWS linux.

`[root@ip-xxx JenkinsTest]# gem list

*** LOCAL GEMS ***

bigdecimal (1.2.0)
colored (1.2)
commander (4.4.3)
file-tail (1.2.0)
filesize (0.1.1)
highline (1.7.8)
inifile (3.0.0)
json (1.8.3)
plist (3.3.0)
psych (2.0.0)
rdoc (4.2.2)
security (0.1.3)
tins (1.15.0)
u3d (1.0.5)`

**Comment by lacostej** [comment]
I made some tests on a system ruby on a Mac and I reproduce the issue.

Updating psych solves it, but there are other issues with using ruby < 2.1

I would recommend using ruby 2.1 or later. There are other issues with ruby 2.0 when coming from the system. E.g. openssl that comes with system.

**Comment by trinistry** [comment]
You are correct, I had ruby version 2.0.0. After upgrading to 2.4.0 the psych error is gone, thank you!

**Comment by lacostej** [comment]
@trinistry Great. Don't hesitate to send some feedback!
